### ISSUE TITLE
Definire un profilo per i CSV

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-guida-ndc-docs#1]
## Mi aspetto

- definire un profilo CSV

## Note
- CSV è descritto da un RFC4180 informativo
- il resto sono raccomandazioni del w3c, eg. https://www.w3.org/TR/tabular-data-primer/#dialects
- la Spagna utilizza un approccio simile (vedi pg. 11) https://datos.gob.es/sites/default/files/doc/file/guia_csv_vf.pdf?fbclid=IwAR25AutHcDrySsCT9b12IgIps2y9CjTS_yaa4xfYl2uIaDi0ZCnko2puu4A --> pagina 11

**Comment by ioggstream** [comment]
Possiamo stabilire che chi processa i CSV DEVE supportare questo profilo:

- tutti i campi vanno quotati con `"`
- il separatore è `,`
- i commenti iniziano con `#` e possono essere saltati
- la riga con l'header è obbligatoria
- i file devono essere encodati in UTF-8

In termini di https://www.w3.org/TR/tabular-data-primer/#well-known-location il descrittore potrebbe essere

```
@context: "http://www.w3.org/ns/csvw"
dialect:
  delimiter: ","
  quoteChar: '"'
  commentPrefix: "#"
  header: true
```

@ronytw @giorgialodi @mfortini
